import Head from "next/head";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="flex flex-col min-h-screen w-screen">
      <Head>
        <title>ATL Landmarks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container w-full sm:max-w-4xl sm:mx-auto p-5 sm:m-3">
        <h1 className="text-stone-900 text-2xl sm:text-3xl font-bold mb-2">
          Civil Rights Landmarks
        </h1>
        <div className="mt-3">
          <iframe
            src="https://www.google.com/maps/d/u/0/embed?mid=1qena5y5E7NRpI_8FIgqFXbBmwgXwpCNI&ehbc=2E312F"
            width="100%"
            height="480"
          ></iframe>
        </div>
        <h1 className="text-stone-900 text-2xl sm:text-3xl font-bold mb-2 mt-6">
          Places to Visit
        </h1>
        <div className="relative bg-red-800">
          <div className="w-full border-2 border-red-800"></div>
        </div>
        <div></div>
      </main>

      <footer></footer>
    </div>
  );
}
